version: "3.4"
services:
  chat-api:
    container_name: chat-api
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db
  chat-app:
    container_name: chat-app
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client/:/app
      - /app/node_modules
    links:
      - chat-api

volumes:
  dbdata:
   driver: local